name: Handle Push Events

on:
  push:
    branches:
      - main

jobs:
  handle_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2

      - name: Check if composer.json version changed
        id: version_check
        run: |
          version=$(jq -r '.version' composer.json)
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          if [ "$version" != "$latest_tag" ]; then
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "version_changed=false" >> $GITHUB_ENV
          fi

      - name: Update release for unchanged version
        if: env.version_changed == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(jq -r '.version' composer.json)
          gh release upload "$version" --notes "Automatically updated with latest changes."

      - name: Create tag and release for new version
        if: env.version_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(jq -r '.version' composer.json)
          git tag "$version"
          git push origin "$version"
          gh release create "$version" --generate-notes --title "$version"
